<?php

use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('jobs')->insert([
            [
                'name_ar' => 'اسم الوظيفة',
                'name_en' => 'Job Name',
                'work_hours' => 8,
                'exper_years' => 4,
                // 'address' => 'الرياض, المملكة العربية السعودية',
                'required_number' => 10,
                'free_places' => 10,
                'description_ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.',
                'description_en' => 'This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of letters generated by the application. If you need more paragraphs, the Arabic text generator can increase the number of paragraphs as you want, the text will not appear divided and does not contain linguistic errors, the Arabic text generator is useful for website designers in particular, where the customer needs in many cases to design the site. Hence, the designer who puts temporary texts for the design of the client in full shape, the role of the Arabic text generator, must save the designer the hassle of searching for alternative text that has nothing to do with the topic that the design talks about in an inappropriate manner. This text can be installed on any design without a problem and will not look like copied, unorganized, unformatted, or even incomprehensible text. Because it is still an alternative and temporary text.',
                'required_age' => 30,
                'salary' => 4000,
                'country_id' => 1,
                'city_id' => 1,
                'user_id' => 1,
            ],
            [
                'name_ar' => 'اسم الوظيفة',
                'name_en' => 'Job Name',
                'work_hours' => 8,
                'exper_years' => 4,
                // 'address' => 'الرياض, المملكة العربية السعودية',
                'required_number' => 10,
                'free_places' => 10,
                'description_ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.',
                'description_en' => 'This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of letters generated by the application. If you need more paragraphs, the Arabic text generator can increase the number of paragraphs as you want, the text will not appear divided and does not contain linguistic errors, the Arabic text generator is useful for website designers in particular, where the customer needs in many cases to design the site. Hence, the designer who puts temporary texts for the design of the client in full shape, the role of the Arabic text generator, must save the designer the hassle of searching for alternative text that has nothing to do with the topic that the design talks about in an inappropriate manner. This text can be installed on any design without a problem and will not look like copied, unorganized, unformatted, or even incomprehensible text. Because it is still an alternative and temporary text.',
                'required_age' => 30,
                'salary' => 4000,
                'country_id' => 1,
                'city_id' => 1,
                'user_id' => 1,
            ],
            [
                'name_ar' => 'اسم الوظيفة',
                'name_en' => 'Job Name',
                'work_hours' => 8,
                'exper_years' => 4,
                // 'address' => 'الرياض, المملكة العربية السعودية',
                'required_number' => 10,
                'free_places' => 10,
                'description_ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.',
                'description_en' => 'This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of letters generated by the application. If you need more paragraphs, the Arabic text generator can increase the number of paragraphs as you want, the text will not appear divided and does not contain linguistic errors, the Arabic text generator is useful for website designers in particular, where the customer needs in many cases to design the site. Hence, the designer who puts temporary texts for the design of the client in full shape, the role of the Arabic text generator, must save the designer the hassle of searching for alternative text that has nothing to do with the topic that the design talks about in an inappropriate manner. This text can be installed on any design without a problem and will not look like copied, unorganized, unformatted, or even incomprehensible text. Because it is still an alternative and temporary text.',
                'required_age' => 30,
                'salary' => 4000,
                'country_id' => 1,
                'city_id' => 1,
                'user_id' => 1,
            ],
            [
                'name_ar' => 'اسم الوظيفة',
                'name_en' => 'Job Name',
                'work_hours' => 8,
                'exper_years' => 4,
                // 'address' => 'الرياض, المملكة العربية السعودية',
                'required_number' => 10,
                'free_places' => 10,
                'description_ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.',
                'description_en' => 'This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of letters generated by the application. If you need more paragraphs, the Arabic text generator can increase the number of paragraphs as you want, the text will not appear divided and does not contain linguistic errors, the Arabic text generator is useful for website designers in particular, where the customer needs in many cases to design the site. Hence, the designer who puts temporary texts for the design of the client in full shape, the role of the Arabic text generator, must save the designer the hassle of searching for alternative text that has nothing to do with the topic that the design talks about in an inappropriate manner. This text can be installed on any design without a problem and will not look like copied, unorganized, unformatted, or even incomprehensible text. Because it is still an alternative and temporary text.',
                'required_age' => 30,
                'salary' => 4000,
                'country_id' => 1,
                'city_id' => 1,
                'user_id' => 1,
            ],
        ]);
    }
}
