<?php

use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('settings')->insert([
            'location_ar' => 'الرياض، المملكة العربية السعودية',
            'location_en' => 'Al Riyadh, Saudi Arabia Kingdom',
            'phone' => '+12345678900',
            'email' => 'sitename@gmail.com',

            'welcome_text_ar' => 'مرحباَ بك فى موقع وسيط المعلم ... !',
            'welcome_text_en' => 'Welcome to Waseet Al Moalm ...!',

            'header_logo' => 'http://127.0.0.1:8000/images/logo2.png',

            'text_before_add_ar' => 'التميز و الإحترافية فى تقديم الخدمات للباحثين عن الوظائف التعليمية',
            'text_before_add_en' => 'Excellence and professionalism in providing services to those looking for educational jobs',
           
            'text_after_add_ar' => 'نسعى لتقديم الخيارات المتعددة من الوظائف التعليمية عبر بوابة تقنية بمعايير عالمية لنكون الوسيط بين الباحثين عن العمل و المنشآت التعليمية للإستفادة من الخبرات و الكفاءاتكام نقوم بتقديم عدد من الحقائب التعليمية لتساعد المعلم فى تطوير مهاراتة التعليمية بكفاءة عالية.',
            'text_after_add_en' => 'We seek to provide multiple options of educational jobs through a technical portal with international standards to be the mediator between job seekers and educational facilities to take advantage of expertise and competencies. We also provide a number of educational bags to help the teacher develop his educational skills with high efficiency.',
            
            'text_after_add_image' => 'http://127.0.0.1:8000/images/logo.png',

            'section_1_image' => 'http://127.0.0.1:8000/images/section1.png',
            
            'section_1_title_ar' => 'البحث عن عمل',
            'section_1_title_en' => 'Job search',
           
            'section_1_text_ar' => 'لتسهيل عملية البحث عن الوظائف المتاحة',
            'section_1_text_en' => 'To facilitate the search for available jobs',

            'step_1_image' => 'http://127.0.0.1:8000/images/download2.png',

            'step_1_title_ar' => 'العنوان الأول',
            'step_1_title_en' => 'First title',

            'step_1_text_ar' => 'النص الأول',
            'step_1_text_en' => 'First text',  

            'step_2_image' => 'http://127.0.0.1:8000/images/download3.png',

            'step_2_title_ar' => 'العنوان الثانى',
            'step_2_title_en' => 'Second title',

            'step_2_text_ar' => 'النص الثانى',
            'step_2_text_en' => 'Second text',

            'step_3_image' => 'http://127.0.0.1:8000/images/download4.png',

            'step_3_title_ar' => 'العنوان الثالث',
            'step_3_title_en' => 'Third title',

            'step_3_text_ar' => 'النص الثالث',
            'step_3_text_en' => 'Third text',

            'section_2_image' => 'http://127.0.0.1:8000/images/section2.png',
            
            'section_2_title_ar' => 'المعلم الخصوصى',
            'section_2_title_en' => 'Private teacher',
            
            'section_2_text_ar' => 'لخلق منصة عمل لخريجات الأقسام التربوية و الإستفادة من خبراتهم التعليمية و كفاءاتهم',
            'section_2_text_en' => 'To create a work platform for female graduates of educational departments and to benefit from their educational experiences and competencies',
            
            'section_3_image' => 'http://127.0.0.1:8000/images/section3.png',
            
            'section_3_title_ar' => 'الحقائب التعليمية',
            'section_3_title_en' => 'Educational bags',
            
            'section_3_text_ar' => ' لتساعد المعلم فى طرح المادة التعليمية بطرق مشوقة للطلاب',
            'section_3_text_en' => 'Help the teacher in introducing the educational material in interesting ways for students',
            
            'footer_text_ar' => 'هذا النص هو مثال لنص يمكن ان يستبدل فى نفس المساحه. لقد تم توليد هذا النص من مولد النص العربى. حيث يمكنك ان تولد مثل هذا النص او العديد من النصوص الاخرى اضافة الى زيادة عدد الحروف التى يولدها التطبيق',
            'footer_text_en' => 'This text is an example of text that can be replaced in the same space. This text has been generated from the Arabic text generator. Where you can generate such text or many other texts in addition to increasing the number of letters generated by the application',
            
            'footer_logo' => 'http://127.0.0.1:8000/images/logo3.png',
            
            'contact_us_title_ar' => 'تواصل معنا',
            'contact_us_title_en' => 'Contact us',
            
            'contact_us_text_ar' => 'هذا النص هو مثال لنص يمكن ان يستبدل فى نفس المساحه',
            'contact_us_text_en' => 'This text is an example of text that can be replaced in the same space',
            
            'saved_title_ar' => 'المحفوظات',
            'saved_title_en' => 'Archives',
            
            'saved_text_ar' => 'هذا النص هو مثال لنص يمكن ان يسبدل فى نفس المساحه',
            'saved_text_en' => 'This text is an example of text that can be replaced in the same space',
        ]);
    }
}
