<?php

use Illuminate\Database\Seeder;

class SliderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sliders')->insert([
            [
                'title_ar' => 'مرحباَ بك فى موقع وسيط المعلم',
                'title_en' => 'Welcome to Wasset El Mo3lm website',
                'body_ar' => 'هذا النص من مولد النص العربى. حيث يمكنك ان تولد مثل هذا النص او العديد من النصوص الاخرى اضافة الى زيادة عدد الحروف التى يولدها التطبيق هذا النص من مولد النص العربى. حيث يمكنك ان تولد مثل هذا النص او العديد من النصوص الاخرى اضافة الى زيادة عدد الحروف التى يولدها التطبيق',
                'body_en' => 'This text is an example of text that can be replaced in the same space. This text has been generated from the Arabic text generator. Where you can generate such text or many other texts in addition to increasing the number of letters generated by the application',
            ],
            [
                'title_ar' => 'مرحباَ بك فى موقع وسيط المعلم',
                'title_en' => 'Welcome to Wasset El Mo3lm website',
                'body_ar' => 'هذا النص من مولد النص العربى. حيث يمكنك ان تولد مثل هذا النص او العديد من النصوص الاخرى اضافة الى زيادة عدد الحروف التى يولدها التطبيق هذا النص من مولد النص العربى. حيث يمكنك ان تولد مثل هذا النص او العديد من النصوص الاخرى اضافة الى زيادة عدد الحروف التى يولدها التطبيق',
                'body_en' => 'This text is an example of text that can be replaced in the same space. This text has been generated from the Arabic text generator. Where you can generate such text or many other texts in addition to increasing the number of letters generated by the application',
            ],
            [
                'title_ar' => 'مرحباَ بك فى موقع وسيط المعلم',
                'title_en' => 'Welcome to Wasset El Mo3lm website',
                'body_ar' => 'هذا النص من مولد النص العربى. حيث يمكنك ان تولد مثل هذا النص او العديد من النصوص الاخرى اضافة الى زيادة عدد الحروف التى يولدها التطبيق هذا النص من مولد النص العربى. حيث يمكنك ان تولد مثل هذا النص او العديد من النصوص الاخرى اضافة الى زيادة عدد الحروف التى يولدها التطبيق',
                'body_en' => 'This text is an example of text that can be replaced in the same space. This text has been generated from the Arabic text generator. Where you can generate such text or many other texts in addition to increasing the number of letters generated by the application',
            ],
        ]);
    }
}
